<?php
// this just ensures noone can run this script without going through the application
if( !defined('PIH' ) ) {
    header('HTTP/1.0 404 Not Found');
    exit();
}
?>
<?php
echo $this->_t('Login Content');
?>
<form name="loginform" action="<?php echo $this->url('login')?>" method="post">
<div class="memberform">
<table  align="center" class="membertable" cellspacing="1" cellpadding="0" border="0">
<tr>
	<td colspan="2" class="memberheading"><?php echo $this->t('Login')?></td>
</tr>
<tr>
	<td class="memberlabel"><?php echo $this->t('Username:')?></td>
	<td class="memberfield"><input class="memberinput" type="text" name="username" value="" /></td>
</tr>
<tr>
	<td class="memberlabel"><?php echo $this->t('Password:')?></td>
	<td class="memberfield"><input class="memberinput" type="password" name="password" /></td>
</tr>
<tr>
	<td class="memberlabel">&nbsp;</td>
	<td class="memberfield"><input class="memberinput" type="submit" name="login" value="<?php echo $this->t('Login')?>" /></td>
</tr>
</table>
</div>
</form>
<script language="JavaScript" type="text/javascript">
<!--
document.forms.loginform['username'].focus();
//-->
</script>

