<?php
// this just ensures noone can run this script without going through the application
if( !defined('PIH' ) ) {
    header('HTTP/1.0 404 Not Found');
    exit();
}
?>
<?php
echo $this->_t('Upgrade Content');
echo $this->_t('Upgrade - Logged In Content');
?>
<div class="memberform">
<table class="membertable" cellspacing="1" cellpadding="0" border="0" align="center">
<tr>
	<td colspan="2" class="memberheading"><?php echo $this->t('Upgrade To A ')?><?php echo $this->t($plans['paid']->type_name)?> 
	<?php echo $this->t('Account')?></td>
</tr>
<tr>
	<td class="memberlabel"><?php echo $this->t('Username:')?></td>
	<td class="memberfield"><?php echo $user->username;?></td>
</tr>
<tr>
	<td class="memberlabel"><?php echo $this->t('1 Month')?> @ $<?php echo number_format($config->price_1,2);?></td>
	<td class="memberfield">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but20.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="cmd" value="_xclick-subscriptions">
<input type="hidden" name="business" value="<?php echo $config->paypal_email;?>">
<input type="hidden" name="item_name" value="<?php echo htmlspecialchars($config->sitename);?>">
<input type="hidden" name="item_number" value="<?php echo htmlspecialchars($user->username);?>">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="cancel_return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="notify_url" value="<?php echo $this->url('notify')?>" />
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="a3" value="<?php echo number_format($config->price_1,2);?>">
<input type="hidden" name="p3" value="1">
<input type="hidden" name="t3" value="M">
<input type="hidden" name="src" value="1">
<input type="hidden" name="sra" value="1">
</form>
<!-- end paypal form code -->
	</td>
</tr>

<tr>
	<td class="memberlabel"><?php echo $this->t('3 Months @')?> $<?php echo number_format($config->price_3,2);?></td>
	<td class="memberfield">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but20.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="cmd" value="_xclick-subscriptions">
<input type="hidden" name="business" value="<?php echo $config->paypal_email;?>">
<input type="hidden" name="item_name" value="<?php echo htmlspecialchars($config->sitename);?>">
<input type="hidden" name="item_number" value="<?php echo htmlspecialchars($user->username);?>">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="cancel_return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="notify_url" value="<?php echo $this->url('notify')?>" />
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="a3" value="<?php echo number_format($config->price_3,2);?>">
<input type="hidden" name="p3" value="3">
<input type="hidden" name="t3" value="M">
<input type="hidden" name="src" value="1">
<input type="hidden" name="sra" value="1">
</form>
<!-- end paypal form code -->
	</td>
</tr>

<tr>
	<td class="memberlabel"><?php echo $this->t('6 Months')?> @ $<?php echo number_format($config->price_6,2);?></td>
	<td class="memberfield">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but20.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="cmd" value="_xclick-subscriptions">
<input type="hidden" name="business" value="<?php echo $config->paypal_email;?>">
<input type="hidden" name="item_name" value="<?php echo htmlspecialchars($config->sitename);?>">
<input type="hidden" name="item_number" value="<?php echo htmlspecialchars($user->username);?>">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="cancel_return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="notify_url" value="<?php echo $this->url('notify')?>" />
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="a3" value="<?php echo number_format($config->price_6,2);?>">
<input type="hidden" name="p3" value="6">
<input type="hidden" name="t3" value="M">
<input type="hidden" name="src" value="1">
<input type="hidden" name="sra" value="1">
</form>
<!-- end paypal form code -->
	</td>
</tr>

<tr>
	<td class="memberlabel"><?php echo $this->t('12 Months:')?> $<?php echo number_format($config->price_12,2);?></td>
	<td class="memberfield">
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="image" src="https://www.paypal.com/en_US/i/btn/x-click-but20.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<input type="hidden" name="cmd" value="_xclick-subscriptions">
<input type="hidden" name="business" value="<?php echo $config->paypal_email;?>">
<input type="hidden" name="item_name" value="<?php echo htmlspecialchars($config->sitename);?>">
<input type="hidden" name="item_number" value="<?php echo htmlspecialchars($user->username);?>">
<input type="hidden" name="no_shipping" value="1">
<input type="hidden" name="return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="cancel_return" value="<?php echo $this->url('upgrade')?>">
<input type="hidden" name="notify_url" value="<?php echo $this->url('notify')?>" />
<input type="hidden" name="no_note" value="1">
<input type="hidden" name="currency_code" value="USD">
<input type="hidden" name="a3" value="<?php echo number_format($config->price_12,2);?>">
<input type="hidden" name="p3" value="12">
<input type="hidden" name="t3" value="M">
<input type="hidden" name="src" value="1">
<input type="hidden" name="sra" value="1">
</form>
<!-- end paypal form code -->
	</td>
</tr>


</table>
</div>
<?php

if( $this->app->config->upgrade_show_plans ) {
	echo $this->render('plans');
}
